# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 441946a616781e211bd3041200691094edaa236118f6b023c36bb5e849d371d1dea70055e4525b95c15826412cf1a86f8a03aa1f2df6fc61fd48ae1fe14d84a1

test:
  secret_key_base: 1a0e5477efd7e0f7894e5e89e9ef2e575e0ec2db4f0271d9b462f5fa9586ef0ced5e94f33581c1892ba9f03c4e8ab98408897549896639afa00c64027ed8ae30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
